class Locator():
    # For login textbox
    email_textbox_id = "email"
    password_textbox_id = "passwd"
    SubmitLogin_textbox_id = "SubmitLogin"
    # For register textbox
    customer_firstname_textbox_id = "customer_firstname"
    customer_lastname_textbox_id = "customer_lastname"
    customer_password_textbox_id = "passwd"
    firstname_textbox_id = "firstname"
    lastname_textbox_id = "lastname"
    customer_company_textbox_id = "company"
    customer_address1_textbox_id = "address1"
    customer_address2_textbox_id = "address2"
    customer_city_textbox_id = "city"
    customer_postcode_textbox_id = "postcode"
    customer_infor_textbox_id = "other"
    customer_phone_textbox_id = "phone"
    customer_phone_mobile_textbox_id = "phone_mobile"
    customer_alias_textbox_id = "alias"
    customer_gender_textbox_id = "id_gender1"